name: Bug
description: 'Report bug'
assignees: gisellevonbingen
labels: bug
body:
  - type: input
    attributes:
      label: Minecraft Version
      description: 'your minecraft version'
      placeholder: e.g. 1.16.5, 1.18.1
    validations:
      required: true
  - type: input
    attributes:
      label: Forge Version
      description: 'your forge version'
      placeholder: e.g. 36.2.5, 39.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: Space-BossTools Version or AstroCraft Version
      description: 'parent mod version'
      placeholder: e.g. 1.16.5-5.5
    validations:
      required: true
  - type: textarea
    attributes:
      label: The details
      description: Reproduce steps, Crash Report, etc.
